print('TEOREMA DE PITAGORAS(comprimento da hipotenusa)')
co = float(input('Comprimento do cateto oposto:'))
ca = float(input('Comprimento do cateto adjacente:'))
h = (co**2+ ca**2)**(1/2)
print('O comprimento da hipotenusa é igual a {:.2f}'.format(h))
